# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "qa" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Install all software needed 
        run: |
          sudo apt-get update
          sudo apt-get install jq
          sudo apt-get install openjdk-11-jdk
          sudo apt-get install wget
          sudo apt-get install unzip
          sudo "cd /opt; wget https://archive.apache.org/dist/nifi/1.16.3/nifi-toolkit-1.16.3-bin.zip"
          sudo "cd /opt; unzip nifi-toolkit-1.16.3-bin.zip; rm -f /opt/nifi-toolkit-1.16.3-bin.zip"
          # Get Bucket Id from source (dev bucket)
          cd /opt; bucketId=$(./bin/cli.sh registry list-buckets -u http://54.216.211.110:18080 -ot json | jq '.[] | select(.name|test("dev")).identifier')
          flows=$(./bin/cli.sh registry list-flows -b ${bucketid} -u http://54.216.211.110:18080 -ot json | jq '.[].identifier')
          # Get pgId using the flowId obteined in the registry
          flowId=$(echo $flows | sed 's/\"//g');
          for flow in $flowId; do flowVersion=$(./bin/cli.sh nifi pg-list -u http://52.208.110.211:8443 -ot json | jq '.[] | select(.versionControlInformation.flowId=="'"$flow"'").versionControlInformation.version'); ./bin/cli.sh nifi pg-import -b ${bucketId} -f ${flow} -fv ${flowVersion} --registryClientId 4c2b988e-0183-1000-08cc-7bbc53445064 -u http://52.208.110.211:8443 ; done
          
          
          
